// File generated by FlutterFire CLI.
// $ flutterfire configure
//
// IMPORTANT: For development, using dummy Firebase project credentials.
// Replace these with actual credentials from your Firebase Console after Phase 1.
//
// To get real credentials:
// 1. Go to https://console.firebase.google.com
// 2. Create a new project "szybkafucha-production"
// 3. Add iOS app (bundle ID: pl.szybkafucha.mobile)
// 4. Add Android app (package name: pl.szybkafucha.mobile)
// 5. Download GoogleService-Info.plist and google-services.json
// 6. Update the values below

import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // DEVELOPMENT: Using Firebase emulator credentials
  // These are test credentials that work with Firebase emulator suite
  // For production, replace with real credentials from Firebase Console
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRQsvolBBXKSeXl2a4vDPoPYc5sKqL0M',
    appId: '1:338154143619:android:7f427971139229a8f0fd68',
    messagingSenderId: '338154143619',
    projectId: 'szybkafucha-dev',
    storageBucket: 'szybkafucha-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRQsvolBBXKSeXl2a4vDPoPYc5sKqL0M',
    appId: '1:338154143619:ios:9d7d8f5e4c3b2a1g9f0h7i',
    messagingSenderId: '338154143619',
    projectId: 'szybkafucha-dev',
    storageBucket: 'szybkafucha-dev.appspot.com',
    iosBundleId: 'pl.szybkafucha.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaRQsvolBBXKSeXl2a4vDPoPYc5sKqL0M',
    appId: '1:338154143619:ios:9d7d8f5e4c3b2a1g9f0h7i',
    messagingSenderId: '338154143619',
    projectId: 'szybkafucha-dev',
    storageBucket: 'szybkafucha-dev.appspot.com',
    iosBundleId: 'pl.szybkafucha.mobile',
  );
}
