// File generated by FlutterFire CLI.
// $ flutterfire configure

import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    appId: '1:xxxxxxxxxxxxx:android:xxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    messagingSenderId: 'xxxxxxxxxxxxx', // TO BE REPLACED
    projectId: 'szybkafucha-production', // TO BE REPLACED
    storageBucket: 'szybkafucha-production.appspot.com', // TO BE REPLACED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    appId: '1:xxxxxxxxxxxxx:ios:xxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    messagingSenderId: 'xxxxxxxxxxxxx', // TO BE REPLACED
    projectId: 'szybkafucha-production', // TO BE REPLACED
    storageBucket: 'szybkafucha-production.appspot.com', // TO BE REPLACED
    iosBundleId: 'pl.szybkafucha.mobile', // TO BE REPLACED
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    appId: '1:xxxxxxxxxxxxx:ios:xxxxxxxxxxxxxxxxxxxxx', // TO BE REPLACED
    messagingSenderId: 'xxxxxxxxxxxxx', // TO BE REPLACED
    projectId: 'szybkafucha-production', // TO BE REPLACED
    storageBucket: 'szybkafucha-production.appspot.com', // TO BE REPLACED
    iosBundleId: 'pl.szybkafucha.mobile', // TO BE REPLACED
  );
}
