// File generated by FlutterFire CLI.
// $ flutterfire configure
//
// Firebase credentials for szybkafucha-e695b project
// Generated: 2026-01-21

import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // iOS Configuration
  // Project: szybkafucha-e695b
  // From GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWMHcWcsMv3d3XEv7BrWGPg1nYK2cQ_E',
    appId: '1:463172954504:ios:4e36ebb4f9cf2dfb5c323d',
    messagingSenderId: '463172954504',
    projectId: 'szybkafucha-e695b',
    storageBucket: 'szybkafucha-e695b.firebasestorage.app',
    iosBundleId: 'pl.szybkafucha.mobile',
  );

  // Android Configuration
  // TODO: Download google-services.json from Firebase Console
  // Project: szybkafucha-e695b
  // Add this when android app is created in Firebase
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWMHcWcsMv3d3XEv7BrWGPg1nYK2cQ_E',
    appId: '1:463172954504:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '463172954504',
    projectId: 'szybkafucha-e695b',
    storageBucket: 'szybkafucha-e695b.firebasestorage.app',
  );

  // macOS Configuration (same as iOS for now)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWMHcWcsMv3d3XEv7BrWGPg1nYK2cQ_E',
    appId: '1:463172954504:ios:4e36ebb4f9cf2dfb5c323d',
    messagingSenderId: '463172954504',
    projectId: 'szybkafucha-e695b',
    storageBucket: 'szybkafucha-e695b.firebasestorage.app',
    iosBundleId: 'pl.szybkafucha.mobile',
  );
}
